name: deaf
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Essential Flutter packages
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  camera: ^0.11.1 
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_webrtc: ^0.12.11
  permission_handler: ^11.0.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  file_picker: ^8.3.2
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.2
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  supabase_flutter: 
  path: ^1.9.1
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/icon/
