// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPgiuktZVkUMBKSis6gI7AkFZzJehF4g',
    appId: '1:787838582749:web:25c011f60d47f29f5ec034',
    messagingSenderId: '787838582749',
    projectId: 'images-37928',
    authDomain: 'images-37928.firebaseapp.com',
    storageBucket: 'images-37928.firebasestorage.app',
    measurementId: 'G-G9YRZ03TVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH5ur-g0BmmI_Nr8TfDyHgEPY75mHlbis',
    appId: '1:787838582749:android:6d6e0109f7f1bb1c5ec034',
    messagingSenderId: '787838582749',
    projectId: 'images-37928',
    storageBucket: 'images-37928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhIyjryYCJh89PfleZxNEtIiXzBSEiSBI',
    appId: '1:787838582749:ios:2dce7b88037876e15ec034',
    messagingSenderId: '787838582749',
    projectId: 'images-37928',
    storageBucket: 'images-37928.firebasestorage.app',
    iosBundleId: 'com.example.deaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhIyjryYCJh89PfleZxNEtIiXzBSEiSBI',
    appId: '1:787838582749:ios:2dce7b88037876e15ec034',
    messagingSenderId: '787838582749',
    projectId: 'images-37928',
    storageBucket: 'images-37928.firebasestorage.app',
    iosBundleId: 'com.example.deaf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIPgiuktZVkUMBKSis6gI7AkFZzJehF4g',
    appId: '1:787838582749:web:617fbc70e156ad0f5ec034',
    messagingSenderId: '787838582749',
    projectId: 'images-37928',
    authDomain: 'images-37928.firebaseapp.com',
    storageBucket: 'images-37928.firebasestorage.app',
    measurementId: 'G-3K2M5WPBMT',
  );
}
